/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-25 04:49:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.collection;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class collection_002dmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1670891023399L));
    _jspx_dependants.put("jar:file:/C:/dev_source/Team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>컬렉션 메인</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- SEO Meta Tags-->\r\n");
      out.write("  <meta name=\"description\" content=\"Finder - Directory &amp; Listings Bootstrap Template\">\r\n");
      out.write("  <meta name=\"keywords\"\r\n");
      out.write("    content=\"bootstrap, business, directory, listings, e-commerce, car dealer, city guide, real estate, job board, user account, multipurpose, ui kit, html5, css3, javascript, gallery, slider, touch\">\r\n");
      out.write("  <meta name=\"author\" content=\"Createx Studio\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Viewport-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor Styles-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/simplebar.min.css\" />\r\n");
      out.write(" <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/tiny-slider.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/flatpickr.min.css\" />\r\n");
      out.write("  <!-- Main Theme Styles + Bootstrap  + Page Loading Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/page-loading.css\">\r\n");
      out.write("  <!-- 직접 작성한 Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/common.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/header-footer.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/collection-main.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Page loading spinner-->\r\n");
      out.write("  <div class=\"page-loading active\">\r\n");
      out.write("    <div class=\"page-loading-inner\">\r\n");
      out.write("      <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"page-wrapper\">\r\n");
      out.write("    	\r\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 컬렉션 검색칸-->\r\n");
      out.write("    <section class=\"mb-3\">\r\n");
      out.write("      <!-- 배경이미지, 불투명도-->\r\n");
      out.write("\r\n");
      out.write("      <!-- 배경이미지, 크기, 불투명도-->\r\n");
      out.write("      <div class=\"jarallax bg-dark\" data-jarallax data-speed=\"0.5\" style=\"height: 270px;\">\r\n");
      out.write("        <span class=\"img-overlay bg-transparent opacity-80\"\r\n");
      out.write("          style=\"background-image: linear-gradient(0deg, rgba(31, 27, 45, .7), rgba(31, 27, 45, .7));\"></span>\r\n");
      out.write("        <div class=\"jarallax-img\" style=\"background-image: url(img/경복궁_근정전_내부_어좌.jpg);\"></div>\r\n");
      out.write("        <div class=\"row content-overlay d-flex justify-content-center align-items-end\"\r\n");
      out.write("          style=\"height: 170px; padding-top: 140px;\">\r\n");
      out.write("          <!-- 배경박스-->\r\n");
      out.write("          <div class=\"content-overlay d-block justify-content-center text-center bg-white border-top\"\r\n");
      out.write("            style=\"width: 1200px; height: 140px; border-radius: 40px;\">\r\n");
      out.write("            <!-- 입력박스-->\r\n");
      out.write("            <div class=\"d-block justify-content-center text-center my-2 pt-3 pb-1\">\r\n");
      out.write("              <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                <div class=\"col-11 d-flex align-items-center justify-content-end p-0\">\r\n");
      out.write("                  <div class=\"col-4 d-flex align-items-center justify-content-center\">\r\n");
      out.write("                    <h1 class=\" text-center m-0 pe-5\">컬렉션 검색</h1>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-7 d-flex justify-content-between\">\r\n");
      out.write("                    <form class=\"bg-white d-flex position-relative rounded-md-pill p-1 col-sch-form\"\r\n");
      out.write("                      style=\"border: 1px solid rgba(126, 126, 126, 0.521);\">\r\n");
      out.write("                      <div class=\"input-group input-group-lg \">\r\n");
      out.write("                        <span class=\"input-group-text text-muted rounded-pill border-0 ms-3 p-1 \">\r\n");
      out.write("                          <i class=\"fi-search\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <!-- 컬렉션 입력창-->\r\n");
      out.write("                        <input class=\"form-control border-0 ms-3 p-1 col-sch-input\" type=\"text\" placeholder=\"컬렉션 입력\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-sm-flex\">\r\n");
      out.write("                        <button\r\n");
      out.write("                          class=\"btn btn-primary btn-lg rounded-pill w-100 w-md-auto ms-sm-3 col-sch-btn px-4 py-0\"\r\n");
      out.write("                          type=\"button\">검색하기</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 정렬 선택-->\r\n");
      out.write("            <div class=\"content-overlay d-block justify-content-center mb-5 d-flex\">\r\n");
      out.write("              <div class=\"row \" style=\"height: 55px; width:1200px;\">\r\n");
      out.write("                <div class=\"col-12 bg-white\">\r\n");
      out.write("                  <div class=\"d-flex flex-md-row flex-column align-items-md-center justify-content-md-between my-2\">\r\n");
      out.write("                    <div class=\"col-8 d-flex align-items-sm-center ps-5\">\r\n");
      out.write("                      <hr class=\"\" style=\"border: .5px solid rgba(108, 108, 108, 0.389); width: 1400px;\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Sort-->\r\n");
      out.write("                    <div class=\"d-flex align-items-sm-center align-items-end\">\r\n");
      out.write("                      <div class=\"d-flex flex-sm-row flex-column align-items-sm-center w-100 pe-sm-5\">\r\n");
      out.write("                        <label class=\"mb-sm-0 mb-2 me-sm-2 pe-sm-1 text-nowrap\" for=\"sortby\"><i\r\n");
      out.write("                            class=\"fi-arrows-sort me-2\"></i>정렬 선택 :</label>\r\n");
      out.write("                        <select class=\"form-select form-select-sm\" id=\"sortby\" style=\"min-width: 180px;\">\r\n");
      out.write("                          <option>좋아요순</option>\r\n");
      out.write("                          <option>일별 조회순</option>\r\n");
      out.write("                          <option>누적 조회순</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- <a class=\"d-inline-block ms-sm-4 ms-3 mb-sm-0 mb-2 fs-sm fw-bold text-decoration-none text-nowrap\" href=\"#\"><i class=\"fi-x fs-xs me-2 align-middle\"></i>Clear all</a> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 주간 베스트 컬렉션 -->\r\n");
      out.write("    <section class=\"container mb-lg-4 mt-3\" style=\"padding: 0px 100px;\">\r\n");
      out.write("      <div class=\"d-flex align-items-center justify-content-between mb-2 pb-2\">\r\n");
      out.write("        <h2 class=\"h2 mb-0 ps-1\">주간 베스트 컬렉션</h2>\r\n");
      out.write("        <!-- <a class=\"btn btn-link fw-bold ms-sm-3 pe-1\" href=\"#\">더보러가기\r\n");
      out.write("          <i class=\"fi-arrow-long-right ms-2\"></i></a> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"tns-carousel-wrapper tns-controls-outside-xxl tns-nav-outside mb-xxl-2 px-2\">\r\n");
      out.write("        <div class=\"tns-carousel-inner\"\r\n");
      out.write("          data-carousel-options=\"{&quot;items&quot;: 3, &quot;gutter&quot;: 24, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1,&quot;nav&quot;:true},&quot;500&quot;:{&quot;items&quot;:2},&quot;850&quot;:{&quot;items&quot;:3},&quot;1400&quot;:{&quot;items&quot;:2,&quot;nav&quot;:false}}}\">\r\n");
      out.write("          <!-- item 1-->\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div class=\"position-relative mb-2 col-main-box\">\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"rounded-4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"h4 mb-2\">\r\n");
      out.write("              <a class=\"nav-link stretched-link text-center\" href=\"#\">문화재컬렉션 1</a>\r\n");
      out.write("            </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- item 2-->\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div class=\"position-relative mb-2 col-main-box\">\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"rounded-4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"h4 mb-2\">\r\n");
      out.write("              <a class=\"nav-link stretched-link text-center\" href=\"#\">문화재컬렉션 2</a>\r\n");
      out.write("            </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- item 3-->\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div class=\"position-relative mb-2 col-main-box\">\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"rounded-4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사3.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"h4 mb-2\">\r\n");
      out.write("              <a class=\"nav-link stretched-link text-center\" href=\"#\">문화재컬렉션 3</a>\r\n");
      out.write("            </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- item 4-->\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div class=\"position-relative mb-2 col-main-box\">\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"rounded-4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경주_불국사_다보탑.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"h4 mb-2\">\r\n");
      out.write("              <a class=\"nav-link stretched-link text-center\" href=\"#\">문화재컬렉션 4</a>\r\n");
      out.write("            </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- item 5-->\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div class=\"position-relative mb-2 col-main-box\">\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"rounded-4\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_전경.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"h4 mb-2\">\r\n");
      out.write("              <a class=\"nav-link stretched-link text-center\" href=\"#\">문화재컬렉션 5</a>\r\n");
      out.write("            </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 이달의 수집가 -->\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"container mt-2\" style=\"padding: 0px 100px;\">\r\n");
      out.write("        <div class=\"d-sm-flex align-items-center justify-content-between pb-2 mb-sm-2\">\r\n");
      out.write("          <h2 class=\"h3 mb-sm-0 \">이달의 인기 수집가</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 1행 -->\r\n");
      out.write("        <div class=\"col-12 mt-1\">\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div class=\"card card-hover mb-2 shadow-sm\" style=\"border-radius: 50px;\">\r\n");
      out.write("            <div class=\"card-body p-2\">\r\n");
      out.write("              <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"d-flex align-items-center ps-4\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center month-pp\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <img class=\"d-none d-sm-block rounded-circle\" src=\"img/행사3.JPG\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"ps-sm-3\">\r\n");
      out.write("                    <h3 class=\"h6 card-title pb-1 mb-2\">\r\n");
      out.write("                      <a class=\"text-nav text-decoration-none\" href=\"#\">\r\n");
      out.write("                        <span class=\"me-3 h5\">문화재홀릭남</span>\r\n");
      out.write("                        <!-- <span class=\"badge bg-faded-accent fs-sm rounded-pill\">Featured</span> -->\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-8 d-flex align-items-center justify-content-end \">\r\n");
      out.write("                  <!--리스트1-->\r\n");
      out.write("                  <div class=\"month-col-list d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4 align-items-center\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트2-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트3-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/부여_정림사지_오층석탑_정면_(촬영년도___2015년).jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 2행 -->\r\n");
      out.write("        <div class=\"col-12 mt-1\">\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div class=\"card card-hover mb-2 shadow-sm\" style=\"border-radius: 50px;\">\r\n");
      out.write("            <div class=\"card-body p-2\">\r\n");
      out.write("              <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"d-flex align-items-center ps-4\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center month-pp\">\r\n");
      out.write("                    <img class=\"d-none d-sm-block rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"ps-sm-3\">\r\n");
      out.write("                    <h3 class=\"h6 card-title pb-1 mb-2\">\r\n");
      out.write("                      <a class=\"text-nav text-decoration-none\" href=\"#\">\r\n");
      out.write("                        <span class=\"me-3 h5\">둥이엄마</span>\r\n");
      out.write("                        <!-- <span class=\"badge bg-faded-accent fs-sm rounded-pill\">Featured</span> -->\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-8 d-flex align-items-center justify-content-end \">\r\n");
      out.write("                  <!--리스트1-->\r\n");
      out.write("                  <div class=\"month-col-list d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4 align-items-center\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트2-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트3-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/부여_정림사지_오층석탑_정면_(촬영년도___2015년).jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 3행 -->\r\n");
      out.write("        <div class=\"col-12 mt-1\">\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div class=\"card card-hover mb-2 shadow-sm\" style=\"border-radius: 50px;\">\r\n");
      out.write("            <div class=\"card-body p-2\">\r\n");
      out.write("              <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"d-flex align-items-center ps-4\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center month-pp\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <img class=\"d-none d-sm-block rounded-circle\" src=\"img/행사3.JPG\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"ps-sm-3\">\r\n");
      out.write("                    <h3 class=\"h6 card-title pb-1 mb-2\">\r\n");
      out.write("                      <a class=\"text-nav text-decoration-none\" href=\"#\">\r\n");
      out.write("                        <span class=\"me-3 h5\">혼자잘간다</span>\r\n");
      out.write("                        <!-- <span class=\"badge bg-faded-accent fs-sm rounded-pill\">Featured</span> -->\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-8 d-flex align-items-center justify-content-end \">\r\n");
      out.write("                  <!--리스트1-->\r\n");
      out.write("                  <div class=\"month-col-list d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4 align-items-center\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트2-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--리스트3-->\r\n");
      out.write("                  <div class=\"month-col-list\">\r\n");
      out.write("                    <div class=\"position-relative text-center me-4\">\r\n");
      out.write("                      <button\r\n");
      out.write("                        class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                        type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                        data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                        <i class=\"fi-heart\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/부여_정림사지_오층석탑_정면_(촬영년도___2015년).jpg\">\r\n");
      out.write("                      <h4 class=\"h4 m-0 mt-1\">\r\n");
      out.write("                        <a class=\"nav-link stretched-link\" href=\"#\">컬렉션1</a>\r\n");
      out.write("                      </h4>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--조회수 탑50 컬렉션 -->\r\n");
      out.write("    <section class=\"container mb-5 mt-5\" style=\"padding: 0px 100px;\">\r\n");
      out.write("      <div class=\"d-sm-flex align-items-center justify-content-between pb-2 mb-sm-2\">\r\n");
      out.write("        <h2 class=\"h3 mb-sm-0\">주간 조회수 TOP 50</h2><a class=\"btn btn-link fw-bold p-0\" href=\"#\">더보러가기<i\r\n");
      out.write("            class=\"fi-arrow-long-right ms-2\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- item 1 -->\r\n");
      out.write("        <div class=\"col-md-3 \" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 2 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 3 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 4 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_제70호_훈민정음(2014년_국보_동산_앱사진).jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--지금뜨는 컬렉션 -->\r\n");
      out.write("    <section class=\"container mb-2 mt-3\" style=\"padding: 0px 100px;\">\r\n");
      out.write("      <div class=\"d-sm-flex align-items-center justify-content-between pb-2 mb-sm-2\">\r\n");
      out.write("        <h2 class=\"h3 mb-sm-0\">주간 조회수 TOP 50</h2><a class=\"btn btn-link fw-bold p-0\" href=\"#\">더보러가기<i\r\n");
      out.write("            class=\"fi-arrow-long-right ms-2\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- item 1 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 2 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 3 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item 4 -->\r\n");
      out.write("        <div class=\"col-md-3\" style=\"height: 350px;\">\r\n");
      out.write("          <article class=\"card card-hover border-0 shadow h-100\">\r\n");
      out.write("            <a class=\"card-img-top overflow-hidden position-relative \" href=\"#\">\r\n");
      out.write("              <!-- <span class=\"badge bg-faded-info position-absolute top-0 end-0 fs-sm rounded-pill m-3\">New</span> -->\r\n");
      out.write("              <button\r\n");
      out.write("                class=\"btn btn-icon btn-light-primary btn-xs text-primary rounded-circle position-absolute top-0 end-0 m-3 zindex-5 \"\r\n");
      out.write("                type=\"button\" data-bs-toggle=\"tooltip\" data-bs-placement=\"left\"\r\n");
      out.write("                data-bs-original-title=\"Add to Favorites\">\r\n");
      out.write("                <i class=\"fi-heart\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <img class=\"d-block col-top-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_제70호_훈민정음(2014년_국보_동산_앱사진).jpg\" alt=\"Image\"></a>\r\n");
      out.write("            <div class=\"card-body pb-3\">\r\n");
      out.write("              <h3 class=\"fs-base pt-1 mb-2\"><a class=\"nav-link\" href=\"#\">반가사유사유사유사유상</a></h3>\r\n");
      out.write("            </div><a class=\"card-footer d-flex align-items-center text-decoration-none border-top-0 pt-0 mb-1\" href=\"#\">\r\n");
      out.write("              <div class=\"d-flex align-items-center col-top-pp\">\r\n");
      out.write("                <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.JPG\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-2\">\r\n");
      out.write("                <h6 class=\"fs-sm text-nav lh-base mb-1\">Bessie Cooper</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </article>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("  <footer class=\"footer pt-lg-5 pt-4 footer_color text-light\">\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <hr />\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <div class=\"footer_expression\">\r\n");
      out.write("      © Front. 2021 Htmlstream. All rights reserved.<br>\r\n");
      out.write("\r\n");
      out.write("      When you visit or interact with our sites, services or tools, we or our authorised service providers may use\r\n");
      out.write("      cookies for storing information to <br>\r\n");
      out.write("      help provide you with a better, faster and safer experience and for marketing purposes.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"py-4 border-top border-light\">\r\n");
      out.write("      <div class=\"container d-flex flex-column flex-lg-row align-items-center justify-content-between py-2\">\r\n");
      out.write("        <!-- Copyright-->\r\n");
      out.write("        <p class=\"order-lg-1 order-2 fs-sm mb-2 mb-lg-0\"><span class=\"text-light opacity-60\">&copy; All rights\r\n");
      out.write("            reserved. Made by </span><a class=\"nav-link-light fw-bold\" href=\"https://createx.studio/\" target=\"_blank\"\r\n");
      out.write("            rel=\"noopener\">Createx Studio</a></p>\r\n");
      out.write("        <div class=\"d-flex flex-lg-row flex-column align-items-center order-lg-2 order-1 ms-lg-4 mb-lg-0 mb-4\">\r\n");
      out.write("          <!-- Links-->\r\n");
      out.write("          <div class=\"d-flex flex-wrap fs-sm mb-lg-0 mb-4 pe-lg-4\"><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">About</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Blog</a><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">Support</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Contacts</a></div>\r\n");
      out.write("          <div class=\"d-flex align-items-center\">\r\n");
      out.write("            <!-- Language switcher -->\r\n");
      out.write("            <div class=\"dropdown\"><a\r\n");
      out.write("                class=\"nav-link nav-link-light dropdown-toggle fs-sm align-items-center p-0 fw-normal\" href=\"#\"\r\n");
      out.write("                id=\"langSwitcher\" data-bs-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i\r\n");
      out.write("                  class=\"fi-globe mt-n1 me-2 align-middle\"></i>Eng</a>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-dark my-1\" aria-labelledby=\"langSwitcher\">\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"img/flags/de.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Deutsch\">Deutsch</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"img/flags/fr.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Français\">Français</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"img/flags/es.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Español\">Español</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Socials-->\r\n");
      out.write("            <div class=\"ms-4 ps-lg-2 text-nowrap\">\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-facebook\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-twitter\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-telegram\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-messenger\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Back to top button-->\r\n");
      out.write("  <a class=\"btn-scroll-top\" href=\"#top\" data-scroll><span\r\n");
      out.write("      class=\"btn-scroll-top-tooltip text-muted fs-sm me-2\">Top</span><i\r\n");
      out.write("      class=\"btn-scroll-top-icon fi-chevron-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/simplebar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/tiny-slider.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/flatpickr.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/jarallax.min.js\"></script>\r\n");
      out.write("  <!-- Main theme script + Page Loading script -->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/theme.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/page-loading.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/collection/collection-main.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/collection/collection-main.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/collection/collection-main.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
