/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-25 04:49:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.collection;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class collection_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1670891023399L));
    _jspx_dependants.put("jar:file:/C:/dev_source/Team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>컬렉션 리스트</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- SEO Meta Tags-->\r\n");
      out.write("  <meta name=\"description\" content=\"Finder - Directory &amp; Listings Bootstrap Template\">\r\n");
      out.write("  <meta name=\"keywords\"\r\n");
      out.write("    content=\"bootstrap, business, directory, listings, e-commerce, car dealer, city guide, real estate, job board, user account, multipurpose, ui kit, html5, css3, javascript, gallery, slider, touch\">\r\n");
      out.write("  <meta name=\"author\" content=\"Createx Studio\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Viewport-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor Styles-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/simplebar.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/tiny-slider.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/flatpickr.min.css\" />\r\n");
      out.write("  <!-- Main Theme Styles + Bootstrap  + Page Loading Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/page-loading.css\">\r\n");
      out.write("  <!-- 직접 작성한 Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/common.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/header-footer.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/collection-list.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Page loading spinner-->\r\n");
      out.write("  <div class=\"page-loading active\">\r\n");
      out.write("    <div class=\"page-loading-inner\">\r\n");
      out.write("      <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"page-wrapper\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 상단 프로필-->\r\n");
      out.write("    <section class=\"mb-3\">\r\n");
      out.write("      <!-- 배경이미지, 불투명도-->\r\n");
      out.write("\r\n");
      out.write("      <!-- 배경이미지, 크기, 불투명도-->\r\n");
      out.write("      <div class=\"jarallax bg-dark\" style=\"height: 270px;\">\r\n");
      out.write("        <span class=\"img-overlay bg-transparent opacity-80\"\r\n");
      out.write("          style=\"background-image: linear-gradient(0deg, rgba(31, 27, 45, .7), rgba(31, 27, 45, .7));\"></span>\r\n");
      out.write("        <div class=\"jarallax-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_전경.jpg);\"></div>\r\n");
      out.write("        <div class=\"row content-overlay d-flex justify-content-center align-items-end\"\r\n");
      out.write("          style=\"height: 170px; padding-top: 140px;\">\r\n");
      out.write("          <!-- 배경박스-->\r\n");
      out.write("          <div class=\"content-overlay d-block justify-content-center text-center bg-white\"\r\n");
      out.write("            style=\"width: 1200px; border-top-left-radius:40px; border-top-right-radius:40px;\">\r\n");
      out.write("            <!-- 프로필 사진, 관리하기-->\r\n");
      out.write("            <div class=\"d-block justify-content-center text-center my-2 pt-4\">\r\n");
      out.write("              <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                <div class=\"col-11 d-flex align-items-center justify-content-around p-0\">\r\n");
      out.write("                  <div class=\"col-3 d-flex align-items-center flex-column ps-5\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center p-img mb-3\">\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <img class=\"d-none d-sm-block rounded-circle \" src=\"img/행사3.JPG\">\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-block\">\r\n");
      out.write("                      <a class=\"text-nav text-decoration-none\" href=\"#\">\r\n");
      out.write("                        <span class=\"h4\">문화재홀릭남</span>\r\n");
      out.write("                        <!-- <span class=\"badge bg-faded-accent fs-sm rounded-pill\">Featured</span> -->\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-7 d-flex pb-3 align-content-around flex-column \" style=\"height: 180px;\">\r\n");
      out.write("                    <div class=\"d-flex d-block justify-content-end\">\r\n");
      out.write("                      <button class=\"btn btn-translucent-primary mb-3 me-2\" type=\"button\">관리하기</button>\r\n");
      out.write("                      <!-- <a class=\"h5 d-block block d-flex fw-bold text-decoration-none text-nowrap text-end\"\r\n");
      out.write("                      href=\"#\">관리하기</a> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-block d-flex pt-2 \">\r\n");
      out.write("                      <hr class=\"\" style=\"border: .5px solid rgba(138, 137, 137, 0.389); width: 700px;\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 정렬 선택-->\r\n");
      out.write("    <section class=\"container mb-lg-4 mt-3\" style=\"padding: 80px 100px 0px 100px;\">\r\n");
      out.write("      <div class=\"content-overlay d-block justify-content-end mb-5 d-flex\">\r\n");
      out.write("        <div class=\"row \" style=\"height: 55px; width:600px;\">\r\n");
      out.write("          <div class=\"col-12 bg-white\">\r\n");
      out.write("            <div class=\"d-flex flex-md-row flex-column align-items-md-center justify-content-end my-2\">\r\n");
      out.write("              <div class=\"col-8 d-flex align-items-sm-center ps-5\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Sort-->\r\n");
      out.write("              <div class=\"d-flex align-items-sm-center align-items-end\">\r\n");
      out.write("                <div class=\"d-flex flex-sm-row flex-column align-items-sm-center w-100 pe-sm-5\">\r\n");
      out.write("                  <label class=\"mb-sm-0 mb-2 me-sm-2 pe-sm-1 text-nowrap\" for=\"sortby\">\r\n");
      out.write("                    <i class=\"fi-arrows-sort me-2\"></i>정렬 선택 :</label>\r\n");
      out.write("                  <select class=\"form-select form-select-sm\" id=\"sortby\" style=\"min-width: 180px;\">\r\n");
      out.write("                    <option>좋아요순</option>\r\n");
      out.write("                    <option>조회순</option>\r\n");
      out.write("                    <option>이름순</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 컬렉션 리스트-->\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"container\" style=\" padding: 0 150px;\">\r\n");
      out.write("        <!-- item-->\r\n");
      out.write("        <div class=\"card card-horizontal mb-3\">\r\n");
      out.write("          <!-- 이미지-->\r\n");
      out.write("          <div class=\"col-list \">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 컬렉션 리스트명, 버튼-->\r\n");
      out.write("          <div class=\"align-content-around p-2\" style=\"width: 610px; height: 250px;\">\r\n");
      out.write("            <div class=\"p-2 ps-4 position-absolute\" style=\"width: 610px; height: 135px;\">\r\n");
      out.write("              <h3 class=\"h3 pt-3 mb-2\"><a class=\"nav-link stretched-link\" href=\"city-guide-blog-single.html\">경주빵 먹으면서 보는 코스</a></h3>\r\n");
      out.write("              <p class=\"fs-sm text-muted pt-3\">경주빵 맛있어. 또 먹어</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 좋아고, 댓글 박스-->\r\n");
      out.write("            <div class=\"d-flex flex-row justify-content-around py-3 px-3 ms-2\"\r\n");
      out.write("              style=\"margin-top: 135px; border-top:1px solid rgba(132, 132, 132, 0.395);\">\r\n");
      out.write("              <div class=\"d-inline-block d-flex ps-4\">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:9rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-light text-primary rounded-circle me-2\"><i class=\"fi-chat-circle\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">댓글</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"d-inline-block d-flex \">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:10.5rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-faded-primary text-primary rounded-circle me-2\"><i class=\"fi-heart\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">좋아요</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- item-->\r\n");
      out.write("        <div class=\"card card-horizontal mb-3\">\r\n");
      out.write("          <!-- 이미지-->\r\n");
      out.write("          <div class=\"col-list \">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 컬렉션 리스트명, 버튼-->\r\n");
      out.write("          <div class=\"align-content-around p-2\" style=\"width: 610px; height: 250px;\">\r\n");
      out.write("            <div class=\"p-2 ps-4 position-absolute\" style=\"width: 610px; height: 135px;\">\r\n");
      out.write("              <h3 class=\"h3 pt-3 mb-2\"><a class=\"nav-link stretched-link\" href=\"city-guide-blog-single.html\">경주빵 먹으면서 보는 코스</a></h3>\r\n");
      out.write("              <p class=\"fs-sm text-muted pt-3\">경주빵 맛있어. 또 먹어</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 좋아고, 댓글 박스-->\r\n");
      out.write("            <div class=\"d-flex flex-row justify-content-around py-3 px-3 ms-2\"\r\n");
      out.write("              style=\"margin-top: 135px; border-top:1px solid rgba(132, 132, 132, 0.395);\">\r\n");
      out.write("              <div class=\"d-inline-block d-flex ps-4\">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:9rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-light text-primary rounded-circle me-2\"><i class=\"fi-chat-circle\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">댓글</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"d-inline-block d-flex \">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:10.5rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-faded-primary text-primary rounded-circle me-2\"><i class=\"fi-heart\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">좋아요</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                <!-- item-->\r\n");
      out.write("                <div class=\"card card-horizontal mb-3\">\r\n");
      out.write("                  <!-- 이미지-->\r\n");
      out.write("                  <div class=\"col-list \">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- 컬렉션 리스트명, 버튼-->\r\n");
      out.write("                  <div class=\"align-content-around p-2\" style=\"width: 610px; height: 250px;\">\r\n");
      out.write("                    <div class=\"p-2 ps-4 position-absolute\" style=\"width: 610px; height: 135px;\">\r\n");
      out.write("                      <h3 class=\"h3 pt-3 mb-2\"><a class=\"nav-link stretched-link\" href=\"city-guide-blog-single.html\">경주빵 먹으면서 보는 코스</a></h3>\r\n");
      out.write("                      <p class=\"fs-sm text-muted pt-3\">경주빵 맛있어. 또 먹어</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 좋아고, 댓글 박스-->\r\n");
      out.write("                    <div class=\"d-flex flex-row justify-content-around py-3 px-3 ms-2\"\r\n");
      out.write("                      style=\"margin-top: 135px; border-top:1px solid rgba(132, 132, 132, 0.395);\">\r\n");
      out.write("                      <div class=\"d-inline-block d-flex ps-4\">\r\n");
      out.write("                        <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                          href=\"#\" style=\"width:9rem;\">\r\n");
      out.write("                          <div class=\"icon-box-media bg-light text-primary rounded-circle me-2\"><i class=\"fi-chat-circle\"></i>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">댓글</h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-inline-block d-flex \">\r\n");
      out.write("                        <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                          href=\"#\" style=\"width:10.5rem;\">\r\n");
      out.write("                          <div class=\"icon-box-media bg-faded-primary text-primary rounded-circle me-2\"><i class=\"fi-heart\"></i>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">좋아요</h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                        <!-- item-->\r\n");
      out.write("        <div class=\"card card-horizontal mb-3\">\r\n");
      out.write("          <!-- 이미지-->\r\n");
      out.write("          <div class=\"col-list \">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_제70호_훈민정음(2014년_국보_동산_앱사진).jpg\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 컬렉션 리스트명, 버튼-->\r\n");
      out.write("          <div class=\"align-content-around p-2\" style=\"width: 610px; height: 250px;\">\r\n");
      out.write("            <div class=\"p-2 ps-4 position-absolute\" style=\"width: 610px; height: 135px;\">\r\n");
      out.write("              <h3 class=\"h3 pt-3 mb-2\"><a class=\"nav-link stretched-link\" href=\"city-guide-blog-single.html\">경주빵 먹으면서 보는 코스</a></h3>\r\n");
      out.write("              <p class=\"fs-sm text-muted pt-3\">경주빵 맛있어. 또 먹어</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 좋아고, 댓글 박스-->\r\n");
      out.write("            <div class=\"d-flex flex-row justify-content-around py-3 px-3 ms-2\"\r\n");
      out.write("              style=\"margin-top: 135px; border-top:1px solid rgba(132, 132, 132, 0.395);\">\r\n");
      out.write("              <div class=\"d-inline-block d-flex ps-4\">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:9rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-light text-primary rounded-circle me-2\"><i class=\"fi-chat-circle\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">댓글</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"d-inline-block d-flex \">\r\n");
      out.write("                <a class=\"icon-box card flex-row align-items-center card-hover border-0 rounded-pill py-2 ps-2 pe-4\"\r\n");
      out.write("                  href=\"#\" style=\"width:10.5rem;\">\r\n");
      out.write("                  <div class=\"icon-box-media bg-faded-primary text-primary rounded-circle me-2\"><i class=\"fi-heart\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h3 class=\"icon-box-title fs-4 ps-1 mb-0\">좋아요</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 페이지 넘기기-->\r\n");
      out.write("    <section class=\"my-5\">\r\n");
      out.write("      <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("        <nav aria-label=\"Page navigation example\">\r\n");
      out.write("          <ul class=\"pagination\">\r\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"#\"><i class=\"fi-chevron-left me-2\"></i>Prev</a></li>\r\n");
      out.write("            <li class=\"page-item d-sm-none\"><span class=\"page-link page-link-static\">2 / 5</span></li>\r\n");
      out.write("            <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("            <li class=\"page-item active d-none d-sm-block\" aria-current=\"page\"><span class=\"page-link\">2<span\r\n");
      out.write("                  class=\"visually-hidden\">(current)</span></span></li>\r\n");
      out.write("            <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("            <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("            <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"#\" aria-label=\"Next\">Next<i\r\n");
      out.write("                  class=\"fi-chevron-right ms-2\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("  <footer class=\"footer pt-lg-5 pt-4 footer_color text-light\">\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <hr />\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <div class=\"footer_expression\">\r\n");
      out.write("      © Front. 2021 Htmlstream. All rights reserved.<br>\r\n");
      out.write("\r\n");
      out.write("      When you visit or interact with our sites, services or tools, we or our authorised service providers may use\r\n");
      out.write("      cookies for storing information to <br>\r\n");
      out.write("      help provide you with a better, faster and safer experience and for marketing purposes.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"py-4 border-top border-light\">\r\n");
      out.write("      <div class=\"container d-flex flex-column flex-lg-row align-items-center justify-content-between py-2\">\r\n");
      out.write("        <!-- Copyright-->\r\n");
      out.write("        <p class=\"order-lg-1 order-2 fs-sm mb-2 mb-lg-0\"><span class=\"text-light opacity-60\">&copy; All rights\r\n");
      out.write("            reserved. Made by </span><a class=\"nav-link-light fw-bold\" href=\"https://createx.studio/\" target=\"_blank\"\r\n");
      out.write("            rel=\"noopener\">Createx Studio</a></p>\r\n");
      out.write("        <div class=\"d-flex flex-lg-row flex-column align-items-center order-lg-2 order-1 ms-lg-4 mb-lg-0 mb-4\">\r\n");
      out.write("          <!-- Links-->\r\n");
      out.write("          <div class=\"d-flex flex-wrap fs-sm mb-lg-0 mb-4 pe-lg-4\"><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">About</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Blog</a><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">Support</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Contacts</a></div>\r\n");
      out.write("          <div class=\"d-flex align-items-center\">\r\n");
      out.write("            <!-- Language switcher -->\r\n");
      out.write("            <div class=\"dropdown\"><a\r\n");
      out.write("                class=\"nav-link nav-link-light dropdown-toggle fs-sm align-items-center p-0 fw-normal\" href=\"#\"\r\n");
      out.write("                id=\"langSwitcher\" data-bs-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i\r\n");
      out.write("                  class=\"fi-globe mt-n1 me-2 align-middle\"></i>Eng</a>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-dark my-1\" aria-labelledby=\"langSwitcher\">\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/de.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Deutsch\">Deutsch</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/fr.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Français\">Français</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/es.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Español\">Español</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Socials-->\r\n");
      out.write("            <div class=\"ms-4 ps-lg-2 text-nowrap\">\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-facebook\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-twitter\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-telegram\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-messenger\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Back to top button-->\r\n");
      out.write("  <a class=\"btn-scroll-top\" href=\"#top\" data-scroll><span\r\n");
      out.write("      class=\"btn-scroll-top-tooltip text-muted fs-sm me-2\">Top</span><i\r\n");
      out.write("      class=\"btn-scroll-top-icon fi-chevron-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/simplebar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/tiny-slider.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/flatpickr.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/jarallax.min.js\"></script>\r\n");
      out.write("  <!-- Main theme script + Page Loading script -->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/theme.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/page-loading.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/collection/collection-list.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/collection/collection-list.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/collection/collection-list.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
