/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-26 17:08:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1670891023399L));
    _jspx_dependants.put("jar:file:/C:/dev_source/Team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team2_MVC/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>나만의 박물관</title>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Viewport-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Vendor Styles-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/simplebar.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/tiny-slider.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/flatpickr.min.css\"/>\r\n");
      out.write("  <!-- Main Theme Styles + Bootstrap  + Page Loading Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/page-loading.css\">\r\n");
      out.write("  <!-- 직접 작성한 Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/common.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/header-footer.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/index.css\"> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Page loading spinner-->\r\n");
      out.write("  <div class=\"page-loading active\">\r\n");
      out.write("    <div class=\"page-loading-inner\">\r\n");
      out.write("      <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <main class=\"page-wrapper\">\r\n");
      out.write("    \r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 슬라이더 -->\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"content-overlay container py-md-0 p-0\" style=\"max-width: 100%;\">\r\n");
      out.write("        <div class=\"mb-md-5\">\r\n");
      out.write("          <div class=\"tns-carousel-wrapper\">\r\n");
      out.write("            <div class=\"tns-carousel-inner \" data-carousel-options='{\"gutter\": 16, \"autoplay\": true, \"autoplayTimeout\":3000}'>\r\n");
      out.write("              <div class=\"main-slide one\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/슬라이더배경1.png);\">\r\n");
      out.write("                <div class=\"slide-item d-flex flex-row justify-content-between col-xl-8 col-lg-8 col-md-10 mx-auto mb-sm-0 mb-5 px-0 \">\r\n");
      out.write("                  <div class=\"text-area\">\r\n");
      out.write("                    <!-- 차례대로 text-light, test-white 였음 -->\r\n");
      out.write("                    <p class=\"fs-lg text-dark\">문화재 검색하고, <br/> 컬렉션에 추가하고, <br/> 사람들한테 자랑하자!</p>\r\n");
      out.write("                    <h1 class=\"display-5 text-dark mt-sm-0 my-4\">나만의 컬렉션 만들기</h1>\r\n");
      out.write("                    <a class=\"btn btn-primary btn-sm rounded-pill order-lg-3\" href=\"collection-main.html\">컬렉션 구경하기</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"card-area\">\r\n");
      out.write("                    <!-- <h1>문화재 이미지 들어올 공간. <br/> 만드는 중...</h1> -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"main-slide\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사1.jpg);\">\r\n");
      out.write("                <div class=\"slide-item col-xl-8 col-lg-8 col-md-10 mx-auto mb-sm-5 mb-4 px-0\" style=\"text-align: right;\">\r\n");
      out.write("                  <p class=\"fs-lg text-white\">당신의 곁으로 찾아가는 문화재</p>\r\n");
      out.write("                  <h1 class=\"display-5 text-light mt-sm-0 my-4\">직접 보고 느끼는 문화재 체험</h1>\r\n");
      out.write("                  <a class=\"btn btn-primary btn-sm rounded-pill order-lg-3\" href=\"evevt-main.html\">행사 더 보러가기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"main-slide\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사3.jpg);\">\r\n");
      out.write("                <div class=\"slide-item col-xl-8 col-lg-8 col-md-10 mx-auto mb-sm-5 mb-4 px-0\">\r\n");
      out.write("                  <p class=\"fs-lg text-white\">우리의 것을 찾아가는 여정 <br/> 나도 발걸음을 남기고 싶다면,</p>\r\n");
      out.write("                  <h1 class=\"display-5 text-light mt-sm-0 my-4\">테마별 문화재 투어</h1>\r\n");
      out.write("                  <a class=\"btn btn-primary btn-sm rounded-pill order-lg-3\" href=\"#\">더 알아보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 컬렉션 추천 -->\r\n");
      out.write("    <section class=\"container mb-5 pb-md-4\">\r\n");
      out.write("      <div class=\"d-flex flex-column align-items-center justify-content-between mb-3\">\r\n");
      out.write("        <span class=\"category h5 mb-2\">컬렉션 추천</span>\r\n");
      out.write("        <h2 class=\"h2 mb-0 mx-auto\">이런 문화재는 어때요?</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"tns-carousel-wrapper tns-controls-outside-xxl tns-nav-outside tns-nav-outside-flush mx-n2\">\r\n");
      out.write("        <div class=\"tns-carousel-inner row gx-4 mx-0 pt-3 pb-4\" data-carousel-options=\"{&quot;items&quot;: 4, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1},&quot;500&quot;:{&quot;items&quot;:2},&quot;768&quot;:{&quot;items&quot;:3},&quot;992&quot;:{&quot;items&quot;:5}}}\">\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름1</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름2</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름3</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름4</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름5</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item -->\r\n");
      out.write("          <div class=\"col\">\r\n");
      out.write("            <div class=\"card shadow-sm card-hover border-0\">\r\n");
      out.write("              <div class=\"card-img-top card-img-hover\"><a class=\"img-overlay\" href=\"search-detail.html\"></a>\r\n");
      out.write("                <div class=\"content-overlay end-0 top-0 pt-3 pe-3\"></div>\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"Image\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body position-relative pb-2\">\r\n");
      out.write("                <div class=\"mb-2\"><span class=\"d-table badge bg-success\">국보</span></div>\r\n");
      out.write("                <h3 class=\"h6 mb-2 fs-base\"><a class=\"nav-link stretched-link\" href=\"search-detail.html\">문화재 이름6</a></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- 행사 및 기획전 -->\r\n");
      out.write("    <section class=\"container mb-5 pb-lg-3\">\r\n");
      out.write("      <div class=\"d-flex flex-column align-items-start justify-content-between mb-3\">\r\n");
      out.write("        <span class=\"event category h5 mb-2\">행사 및 기획전</span>\r\n");
      out.write("        <div class=\"w-100 d-flex align-items-center justify-content-between\">\r\n");
      out.write("          <h2 class=\"h2 mb-0\">우리 문화재, 직접 보고 느껴요!</h2>\r\n");
      out.write("          <a class=\"event more btn btn-link ms-md-3 ms-auto p-0 fw-bold\" href=\"evevt-main.html\">더 보러가기<i class=\"fi-arrow-long-right ms-2\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Carousel-->\r\n");
      out.write("      <div class=\"tns-carousel-wrapper tns-controls-outside-xxl tns-nav-outside tns-center\">\r\n");
      out.write("        <div class=\"tns-carousel-inner\" data-carousel-options=\"{&quot;items&quot;: 1, &quot;edgePadding&quot;: true, &quot;responsive&quot;: {&quot;0&quot;:{&quot;controls&quot;: false, &quot;gutter&quot;: 16},&quot;500&quot;:{&quot;controls&quot;: true, &quot;gutter&quot;: 16}, &quot;768&quot;: {&quot;gutter&quot;: 24}}}\">\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"card border-0 bg-size-cover pt-5\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사1.jpg);\">\r\n");
      out.write("              <div class=\"d-none d-md-block\" style=\"height: 10rem;\"></div>\r\n");
      out.write("              <div class=\"card-body text-center text-md-start pt-4 pt-xl-0\">\r\n");
      out.write("                <div class=\"d-md-flex justify-content-between align-items-end\">\r\n");
      out.write("                  <div class=\"me-2 mb-4 mb-md-0\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-center justify-content-md-start text-light fs-sm mb-2\">\r\n");
      out.write("                      <div class=\"text-nowrap me-3\"><i class=\"fi-calendar-alt me-1 opacity-70\"></i><span class=\"align-middle\"> 00월 00일</span></div>\r\n");
      out.write("                      <div class=\"text-nowrap\"><i class=\"fi-clock me-1 opacity-70\"></i><span class=\"align-middle\"> D - 0</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"h2 text-light mb-0\">문화재 행사1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"btn-group\">\r\n");
      out.write("                    <a class=\"ticket btn btn-primary rounded-pill px-5\" href=\"event-detail.html\">예매하기</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"card border-0 bg-size-cover pt-5\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사2.jpg);\">\r\n");
      out.write("              <div class=\"d-none d-md-block\" style=\"height: 10rem;\"></div>\r\n");
      out.write("              <div class=\"card-body text-center text-md-start pt-4 pt-xl-0\">\r\n");
      out.write("                <div class=\"d-md-flex justify-content-between align-items-end\">\r\n");
      out.write("                  <div class=\"me-2 mb-4 mb-md-0\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-center justify-content-md-start text-light fs-sm mb-2\">\r\n");
      out.write("                      <div class=\"text-nowrap me-3\"><i class=\"fi-calendar-alt me-1 opacity-70\"></i><span class=\"align-middle\"> 00월 00일</span></div>\r\n");
      out.write("                      <div class=\"text-nowrap\"><i class=\"fi-clock me-1 opacity-70\"></i><span class=\"align-middle\"> D - 0</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"h2 text-light mb-0\">문화재 행사2</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"btn-group\">\r\n");
      out.write("                    <a class=\"ticket btn btn-primary rounded-pill px-5\" href=\"event-detail.html\">예매하기</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Item-->\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"card border-0 bg-size-cover pt-5\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/행사3.jpg);\">\r\n");
      out.write("              <div class=\"d-none d-md-block\" style=\"height: 10rem;\"></div>\r\n");
      out.write("              <div class=\"card-body text-center text-md-start pt-4 pt-xl-0\">\r\n");
      out.write("                <div class=\"d-md-flex justify-content-between align-items-end\">\r\n");
      out.write("                  <div class=\"me-2 mb-4 mb-md-0\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-center justify-content-md-start text-light fs-sm mb-2\">\r\n");
      out.write("                      <div class=\"text-nowrap me-3\"><i class=\"fi-calendar-alt me-1 opacity-70\"></i><span class=\"align-middle\"> 00월 00일</span></div>\r\n");
      out.write("                      <div class=\"text-nowrap\"><i class=\"fi-clock me-1 opacity-70\"></i><span class=\"align-middle\"> D - 0</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"h2 text-light mb-0\">문화재 행사3</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"btn-group\">\r\n");
      out.write("                    <a class=\"ticket btn btn-primary rounded-pill px-5\" href=\"event-detail.html\">예매하기</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 테마별 문화재 투어 + 커뮤니티 -->\r\n");
      out.write("    <section class=\"container mb-5 pb-lg-3\">\r\n");
      out.write("      <!-- 테마별 문화재 투어 -->\r\n");
      out.write("      <div class=\"bottom-ss\">\r\n");
      out.write("        <div class=\"img-six-box\">\r\n");
      out.write("          <div class=\"mb-2\">\r\n");
      out.write("            <span class=\"category h5 w-100 mb-md-2\">테마별 문화재 투어</span>\r\n");
      out.write("            <h2 class=\"h3 w-100 mb-md-0\">방문 인증하고 스탬프도 받자!</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-content\">\r\n");
      out.write("            <!-- <div class=\"tab-pane fade show active\" id=\"result5\" role=\"tabpane1\"> -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Gallery grid no gutters -->\r\n");
      out.write("            <div class=\"row gallery g-0\">\r\n");
      out.write("              <!-- Item 1-->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"문화재이미지\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지1</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Item 2 -->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"문화재이미지\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지2</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Item 3 -->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"문화재이미지3\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지3</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Item 4 -->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\" alt=\"문화재이미지\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Item 5 -->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/경복궁_근정전_내부_어좌.jpg\" alt=\"Gallery thumbnail\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Item 6 -->\r\n");
      out.write("              <div class=\"col-xl-4 col-sm-6 img-six\">\r\n");
      out.write("                <a href=\"#\" class=\"gallery-item\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/석굴암_본존불2.jpg\" alt=\"문화재이미지\" img-responsive>\r\n");
      out.write("                  <div class=\"carousel-caption text6\">\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                    <h3 class=\"fs-6 text-white text-start\">방문인증코스1</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <span class=\"gallery-item-caption\">문화재이미지</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Add as many columns with gallery item inside as you need -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- </div> -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 커뮤니티 -->\r\n");
      out.write("        <section class=\"community\">\r\n");
      out.write("          <span class=\"category h5 w-100 mb-md-2\">커뮤니티</span>\r\n");
      out.write("          <div class=\"d-md-flex align-items-center justify-content-between mb-2 pb-md-2\">\r\n");
      out.write("            <h2 class=\"h3 w-100 mb-md-0\">자유게시판</h2>\r\n");
      out.write("            <!-- Sorting by date-->\r\n");
      out.write("            <div class=\"w-100 ms-md-3 mb-n3 pt-2 pb-3 px-1\" data-simplebar data-simplebar-auto-hide=\"false\">\r\n");
      out.write("              <div class=\"d-flex align-items-start flex-row-reverse\">\r\n");
      out.write("                <a class=\"more btn btn-link ms-md-3 ms-auto p-0 fw-bold\" href=\"board-free.html\">더 보러가기\r\n");
      out.write("                  <i class=\"fi-arrow-long-right ms-2\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <table class=\"main_community_title\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">[미술]북한사찰들은 안료나 단청양식에서 세세하게... </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">1960년대 도정궁 모습</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">실제 신라 유물로 두는 바둑</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">태종 이방원 세트 건축에 대한 생각</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">[미술사]꼭 봐야 할 이건희 특별전. 어느 수집가의...</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">서원 철폐령 당시에 6개 남기고 다 철폐하였다 하...</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td onClick=\"location.href='board-detail.html'\">국외소재문화재 현황 및 환수가치에 관한 설문조사...</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write(" \r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- Back to top button-->\r\n");
      out.write("  <a class=\"btn-scroll-top\" href=\"#top\" data-scroll><span class=\"btn-scroll-top-tooltip text-muted fs-sm me-2\">Top</span><i class=\"btn-scroll-top-icon fi-chevron-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/simplebar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/tiny-slider.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/flatpickr.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/jarallax.min.js\"></script>\r\n");
      out.write("  <!-- Main theme script + Page Loading script -->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/theme.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/page-loading.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/index.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
