/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-24 19:05:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1670891023399L));
    _jspx_dependants.put("jar:file:/C:/dev_source/Team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>문화재 검색</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- SEO Meta Tags-->\r\n");
      out.write("  <meta name=\"description\" content=\"Finder - Directory &amp; Listings Bootstrap Template\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"bootstrap, business, directory, listings, e-commerce, car dealer, city guide, real estate, job board, user account, multipurpose, ui kit, html5, css3, javascript, gallery, slider, touch\">\r\n");
      out.write("  <meta name=\"author\" content=\"Createx Studio\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Viewport-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor Styles-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/simplebar.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/tiny-slider.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/flatpickr.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/leaflet.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/nouislider.min.css\"/>\r\n");
      out.write("  <!-- Main Theme Styles + Bootstrap  + Page Loading Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/page-loading.css\">\r\n");
      out.write("  <!-- 직접 작성한 Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/common.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/header-footer.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/search.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Page loading spinner-->\r\n");
      out.write("  <div class=\"page-loading active\">\r\n");
      out.write("    <div class=\"page-loading-inner\">\r\n");
      out.write("      <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"page-wrapper\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 문화재 검색칸 -->\r\n");
      out.write("    <section class=\"jarallax bg-dark zindex-1 main-section\" data-jarallax data-speed=\"0.5\">\r\n");
      out.write("      <!-- 배경이미지, 불투명도-->\r\n");
      out.write("      <span class=\"img-overlay bg-transparent opacity-75\"\r\n");
      out.write("        style=\"background-image: linear-gradient(0deg, rgba(31, 27, 45, .7), rgba(31, 27, 45, .7));\">\r\n");
      out.write("      </span>\r\n");
      out.write("      <div class=\"jarallax-img img-main\" style=\"background-image: url(img/경복궁_근정전_내부_어좌.jpg);\"></div>\r\n");
      out.write("      <!-- 문화재 검색칸 문구, 입력창-->\r\n");
      out.write("      <div class=\"content-overlay container content1\">\r\n");
      out.write("        <!-- 문화재 문구 -->\r\n");
      out.write("        <div class=\"col-xl-9 mx-auto mb-4 px-0 text-start\">\r\n");
      out.write("          <p class=\"fs-lg text-white mt-5\">문화재를 검색하고 나만의 컬렉션을 만들자!</p>\r\n");
      out.write("          <h1 class=\"display-6 mt-4 text-white\">문화재 검색</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 검색창-->\r\n");
      out.write("        <div class=\"col-xl-10 mx-auto\">\r\n");
      out.write("          <form class=\"bg-white d-block d-md-flex position-relative rounded-md-pill mb-4 p-2 border-0\">\r\n");
      out.write("            <div class=\"input-group input-group-lg\">\r\n");
      out.write("              <span class=\"input-group-text text-muted rounded-pill border-0 ms-2\">\r\n");
      out.write("                <i class=\"fi-search\"></i>\r\n");
      out.write("              </span>\r\n");
      out.write("              <input class=\"form-control fs-4 border-0\" type=\"text\" placeholder=\"문화재명 입력\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-sm-flex border-0 \">\r\n");
      out.write("              <button class=\"btn btn-search-m rounded-pill ms-sm-3 shadow\" type=\"button\">검색하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("          <!-- 검색 라디오 버튼 -->\r\n");
      out.write("          <div class=\"radio2 text-center m-auto text-white fw-bold\">\r\n");
      out.write("            <label class=\"\" for=\"culturalHeritage-name\">\r\n");
      out.write("              <input class=\"\" type=\"radio\" name=\"culturalHeritage-s\" id=\"culturalHeritage-name\" value=\"option1\" checked>\r\n");
      out.write("              <span>문화재명</span>\r\n");
      out.write("            </label>&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("            <label class=\"\" for=\"culturalHeritage-name-d\">\r\n");
      out.write("              <input class=\"\" type=\"radio\" name=\"culturalHeritage-s\" id=\"culturalHeritage-name-d\" value=\"option2\">\r\n");
      out.write("              <span>문화재명 + 내용</span>\r\n");
      out.write("            </label>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 문화재 검색 필터 -->\r\n");
      out.write("    <section class=\"container mt-5 mb-5\">\r\n");
      out.write("      <aside class=\"col-lg-4 col-xl-3 border-top-lg border-end-lg shadow-sm px-3 px-xl-4 px-xxl-5 pt-lg-2 w-100\"> <!-- border-top-lg border-end-lg shadow-sm -->\r\n");
      out.write("        <div class=\"offcanvas offcanvas-start offcanvas-collapse\" id=\"filters-sidebar\">\r\n");
      out.write("          <!-- ??? -->\r\n");
      out.write("          <div class=\"offcanvas-header d-flex d-lg-none align-items-center\">\r\n");
      out.write("            <h2 class=\"h5 mb-0\">Filters</h2>\r\n");
      out.write("            <button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"offcanvas\"></button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 초기화 버튼 -->\r\n");
      out.write("          <div class=\"border-bottom py-4 text-end\">\r\n");
      out.write("            <button class=\"reset btn btn-outline-primary rounded-pill\" type=\"button\"><i class=\"fi-rotate-right me-2\"></i>초기화</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- 검색 필터들 -->\r\n");
      out.write("          <div class=\"offcanvas-body py-lg-4\">\r\n");
      out.write("            <div class=\"tab-content\">\r\n");
      out.write("              <div class=\"tab-pane fade show active\" id=\"filters\" role=\"tabpanel\">\r\n");
      out.write("                <div class=\"filter d-flex flex-row justify-content-between\">\r\n");
      out.write("                  <!-- 지정종목 -->\r\n");
      out.write("                  <div class=\"pb-4 mb-2\">\r\n");
      out.write("                    <h3 class=\"h6\">지정종목</h3>\r\n");
      out.write("                    <div class=\"overflow-auto\" data-simplebar data-simplebar-auto-hide=\"false\" style=\"height: 15.75rem;\">\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"hotel\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"hotel\">지정종목1</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"hostel\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"hostel\">지정종목2</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"motel\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"motel\">지정종목3</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"apartment\" checked>\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"apartment\">지정종목4</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"cottage\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"cottage\">지정종목5</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"boutique-hotel\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"boutique-hotel\">지정종목6</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"room\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"room\">지정종목7</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"land\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"land\">지정종목8</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"commercial\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"commercial\">지정종목9</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목10</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목11</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목12</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목13</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목14</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking-lot\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking-lot\">지정종목15</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 지역 -->\r\n");
      out.write("                  <div class=\"pb-4 mb-2\">\r\n");
      out.write("                    <h3 class=\"h6\">지역</h3>\r\n");
      out.write("                    <div class=\"overflow-auto\" data-simplebar data-simplebar-auto-hide=\"false\" style=\"height: 15.75rem;\">\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"parking\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"parking\">Parking</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"restaurant\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"restaurant\">Restaurant</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"pet-friendly\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"pet-friendly\">Pet Friendly</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"room-service\" checked>\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"room-service\">Room Service</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"fitness-center\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"fitness-center\">Fitness Center</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"free-wifi\" checked>\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"free-wifi\">Free WiFi</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"spa-lounge\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"spa-lounge\">Spa lounge</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"bar\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"bar\">Bar</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"swimming-pool\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"swimming-pool\">Swimming pool</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 시대 -->\r\n");
      out.write("                  <div class=\"pb-4 mb-2\">\r\n");
      out.write("                    <h3 class=\"h6\">시대</h3>\r\n");
      out.write("                    <div class=\"overflow-auto\" data-simplebar data-simplebar-auto-hide=\"false\" style=\"height: 15.75rem;\">\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"kitchen\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"kitchen\">Kitchen</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"private-bathroom\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"private-bathroom\">Private Bathroom</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"air-conditioning\" checked>\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"air-conditioning\">Air Conditioning</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"desk\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"desk\">Desk</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"terrace\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"terrace\">Terrace</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"washing-machine\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"washing-machine\">Washing Machine</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"heating\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"heating\">Heating</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"laundry-service\">\r\n");
      out.write("                        <label class=\"form-check-label fs-sm\" for=\"laundry-service\">Laundry Service</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 지정연도 + 유형분류 -->\r\n");
      out.write("                  <div class=\"wide\">\r\n");
      out.write("                    <!-- 지정연도 -->\r\n");
      out.write("                    <div class=\"pb-4 mb-2\">\r\n");
      out.write("                      <h3 class=\"h6\">지정연도</h3>\r\n");
      out.write("                      <div class=\"range-slider\" data-start-min=\"300\" data-start-max=\"700\" data-min=\"50\" data-max=\"1000\" data-step=\"20\">\r\n");
      out.write("                        <!-- <div class=\"range-slider-ui\"></div> -->\r\n");
      out.write("                        <div class=\"d-flex align-items-center p-3\">\r\n");
      out.write("                          <div class=\"w-50 pe-2\">\r\n");
      out.write("                            <div class=\"input-group\"><span class=\"input-group-text fs-base\">시작</span>\r\n");
      out.write("                              <input class=\"form-control range-slider-value-min\" type=\"text\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-muted\">&mdash;</div>\r\n");
      out.write("                          <div class=\"w-50 ps-2\">\r\n");
      out.write("                            <div class=\"input-group\"><span class=\"input-group-text fs-base\">끝</span>\r\n");
      out.write("                              <input class=\"form-control range-slider-value-max\" type=\"text\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 유형분류 -->\r\n");
      out.write("                    <div class=\"pb-4 mb-2\">\r\n");
      out.write("                      <h3 class=\"h6\">유형분류</h3>\r\n");
      out.write("                      <div class=\"overflow-auto\" data-simplebar data-simplebar-auto-hide=\"false\" style=\"height: 5rem;\">\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"kitchen\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"kitchen\">Kitchen</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"private-bathroom\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"private-bathroom\">Private Bathroom</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"air-conditioning\" checked>\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"air-conditioning\">Air Conditioning</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"desk\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"desk\">Desk</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"terrace\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"terrace\">Terrace</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"washing-machine\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"washing-machine\">Washing Machine</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"heating\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"heating\">Heating</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          <input class=\"form-check-input\" type=\"checkbox\" id=\"laundry-service\">\r\n");
      out.write("                          <label class=\"form-check-label fs-sm\" for=\"laundry-service\">Laundry Service</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 검색 버튼 -->\r\n");
      out.write("          <div class=\"border-top py-4 text-center\">\r\n");
      out.write("            <button class=\"search btn btn-outline-primary\" type=\"button\"><i class=\"fi-search me-2\"></i>검색</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </aside>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 문화재 검색 결과 -->\r\n");
      out.write("    <section class=\"container mb-5 pb-md-4\">\r\n");
      out.write("      <div class=\"d-flex mb-2 mt-3 re-box\">\r\n");
      out.write("        <!-- 검색 건수 출력-->\r\n");
      out.write("        <div class=\"flex-grow-1\">\r\n");
      out.write("          <span class=\"fs-5 fw-bold\">총 (문화재 검색수)건의 자료가 검색되었습니다.</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 정렬 방법 라디오-->\r\n");
      out.write("        <div class=\"radio3 fs-5 fw-bold\">\r\n");
      out.write("          <label class=\"\" for=\"sort-name\">\r\n");
      out.write("            <input class=\"\" type=\"radio\" name=\"sort\" id=\"sort-name\" value=\"option11\" checked>\r\n");
      out.write("            <span>이름순</span></label>&emsp;\r\n");
      out.write("          <label class=\"\" for=\"sort-date\">\r\n");
      out.write("            <input class=\"\" type=\"radio\" name=\"sort\" id=\"sort-date\" value=\"option22\">\r\n");
      out.write("            <span>지정일순</span></label>&emsp;\r\n");
      out.write("          <label class=\"\" for=\"sort-pop\">\r\n");
      out.write("            <input class=\"\" type=\"radio\" name=\"sort\" id=\"sort-pop\" value=\"option33\">\r\n");
      out.write("            <span>인기순</span></label>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr />\r\n");
      out.write("      <!-- 검색결과 이미지카드 출력 전체칸-->\r\n");
      out.write("      <div class=\"d-flex align-content-start flex-wrap\">\r\n");
      out.write("          <!-- Item1 -->\r\n");
      out.write("          <div class=\"result-item1 shadow \">\r\n");
      out.write("            <div class=\"re-card-img\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/국보_국보_청자_투각칠보문뚜껑_향로.jpg\" alt=\"Image\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex justify-content-between sn-box1\">\r\n");
      out.write("              <div class=\"mt-1\">\r\n");
      out.write("                <span class=\"fs-5\"><a class=\"nav-link\" href=\"#\">반가라라가상</a></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"pt-3 pe-3 fs-xs\">\r\n");
      out.write("                <span class=\"text-muted\"><i class=\"fi-map-pin mt-n1 me-1 fs-base text-muted align-middle\"></i>부여읍\r\n");
      out.write("                  부여성</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--좋아요, 컬렉션-->\r\n");
      out.write("            <div class=\"d-flex justify-content-evenly b2-box\">\r\n");
      out.write("              <div class=\"b2-box-ch ps-4\">\r\n");
      out.write("                <button class=\"btn btn-icon btn-light-primary text-primary rounded-circle\" type=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"tooltip\" data-bs-placement=\"left\" aria-label=\"Remove from Favorites\"\r\n");
      out.write("                  data-bs-original-title=\"Add from Favorites\"><i class=\"fi-heart\"></i></button><span\r\n");
      out.write("                  class=\"fw-bold align-middle\">1165</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"b2-box-ch\">\r\n");
      out.write("                <button class=\"btn btn-icon btn-light-primary text-primary rounded-circle\" type=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"tooltip\" data-bs-placement=\"left\" aria-label=\"Remove from Favorites\"\r\n");
      out.write("                  data-bs-original-title=\"Remove from Favorites\"><i class=\"fi-bookmark align-bottom\"></i></button><span\r\n");
      out.write("                  class=\"fw-bold align-middle\">컬렉션</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div><!-- 결과값 박스-->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 페이지 넘기기-->\r\n");
      out.write("      <div class=\"my-5 d-flex justify-content-center\">\r\n");
      out.write("        <ul class=\"pagination \">\r\n");
      out.write("          <li class=\"page-item\"><a class=\"page-link\" href=\"#\"><i class=\"fi-chevron-left me-2\"></i>Prev</a></li>\r\n");
      out.write("          <li class=\"page-item d-sm-none\"><span class=\"page-link page-link-static\">2 / 5</span></li>\r\n");
      out.write("          <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("          <li class=\"page-item active d-none d-sm-block\" aria-current=\"page\"><span class=\"page-link\">2<span\r\n");
      out.write("                class=\"visually-hidden\">(current)</span></span></li>\r\n");
      out.write("          <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("          <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("          <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("          <li class=\"page-item\"><a class=\"page-link\" href=\"#\" aria-label=\"Next\">Next<i\r\n");
      out.write("                class=\"fi-chevron-right ms-2\"></i></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div> \r\n");
      out.write("      <!-- 페이지 넘기기 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer  -->\r\n");
      out.write("  <footer class=\"footer pt-lg-5 pt-4 footer_color text-light\">\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <hr />\r\n");
      out.write("    <br> <br>\r\n");
      out.write("    <div class=\"footer_expression\">\r\n");
      out.write("      © Front. 2021 Htmlstream. All rights reserved.<br>\r\n");
      out.write("\r\n");
      out.write("      When you visit or interact with our sites, services or tools, we or our authorised service providers may use\r\n");
      out.write("      cookies for storing information to <br>\r\n");
      out.write("      help provide you with a better, faster and safer experience and for marketing purposes.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"py-4 border-top border-light\">\r\n");
      out.write("      <div class=\"container d-flex flex-column flex-lg-row align-items-center justify-content-between py-2\">\r\n");
      out.write("        <!-- Copyright-->\r\n");
      out.write("        <p class=\"order-lg-1 order-2 fs-sm mb-2 mb-lg-0\"><span class=\"text-light opacity-60\">&copy; All rights\r\n");
      out.write("            reserved. Made by </span><a class=\"nav-link-light fw-bold\" href=\"https://createx.studio/\" target=\"_blank\"\r\n");
      out.write("            rel=\"noopener\">Createx Studio</a></p>\r\n");
      out.write("        <div class=\"d-flex flex-lg-row flex-column align-items-center order-lg-2 order-1 ms-lg-4 mb-lg-0 mb-4\">\r\n");
      out.write("          <!-- Links-->\r\n");
      out.write("          <div class=\"d-flex flex-wrap fs-sm mb-lg-0 mb-4 pe-lg-4\"><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">About</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Blog</a><a class=\"nav-link-light px-2 mx-1\"\r\n");
      out.write("              href=\"#\">Support</a><a class=\"nav-link-light px-2 mx-1\" href=\"#\">Contacts</a></div>\r\n");
      out.write("          <div class=\"d-flex align-items-center\">\r\n");
      out.write("            <!-- Language switcher -->\r\n");
      out.write("            <div class=\"dropdown\"><a\r\n");
      out.write("                class=\"nav-link nav-link-light dropdown-toggle fs-sm align-items-center p-0 fw-normal\" href=\"#\"\r\n");
      out.write("                id=\"langSwitcher\" data-bs-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i\r\n");
      out.write("                  class=\"fi-globe mt-n1 me-2 align-middle\"></i>Eng</a>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-dark my-1\" aria-labelledby=\"langSwitcher\">\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/de.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Deutsch\">Deutsch</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/fr.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Français\">Français</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item text-nowrap py-1\" href=\"#\"><img class=\"me-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/flags/es.png\"\r\n");
      out.write("                      width=\"20\" alt=\"Español\">Español</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Socials-->\r\n");
      out.write("            <div class=\"ms-4 ps-lg-2 text-nowrap\">\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-facebook\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-twitter\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-telegram\"></i></a>\r\n");
      out.write("              <a class=\"btn btn-icon btn-translucent-light btn-xs rounded-circle ms-2\" style=\"color:black;\" href=\"#\">\r\n");
      out.write("                <i class=\"fi-messenger\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Back to top button-->\r\n");
      out.write("  <a class=\"btn-scroll-top\" href=\"#top\" data-scroll><span\r\n");
      out.write("      class=\"btn-scroll-top-tooltip text-muted fs-sm me-2\">Top</span><i class=\"btn-scroll-top-icon fi-chevron-up\"></i>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/simplebar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/tiny-slider.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/flatpickr.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/jarallax.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/leaflet.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/nouislider.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Main theme script + Page Loading script -->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/theme.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/page-loading.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/search/search.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/search/search.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search/search.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
