/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-24 19:56:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_002dmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1670891023399L));
    _jspx_dependants.put("jar:file:/C:/dev_source/Team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Team2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>나만의 박물관</title>\r\n");
      out.write("  <!-- Viewport-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!-- Page loading styles-->\r\n");
      out.write("  <style>\r\n");
      out.write("    .page-loading {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      right: 0;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      -webkit-transition: all .4s .2s ease-in-out;\r\n");
      out.write("      transition: all .4s .2s ease-in-out;\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      visibility: hidden;\r\n");
      out.write("      z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-loading.active {\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("      visibility: visible;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-loading-inner {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      -webkit-transform: translateY(-50%);\r\n");
      out.write("      transform: translateY(-50%);\r\n");
      out.write("      -webkit-transition: opacity .2s ease-in-out;\r\n");
      out.write("      transition: opacity .2s ease-in-out;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-loading.active>.page-loading-inner {\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-loading-inner>span {\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-size: 1rem;\r\n");
      out.write("      font-weight: normal;\r\n");
      out.write("      color: #666276;\r\n");
      out.write("      ;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-spinner {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      width: 2.75rem;\r\n");
      out.write("      height: 2.75rem;\r\n");
      out.write("      margin-bottom: .75rem;\r\n");
      out.write("      vertical-align: text-bottom;\r\n");
      out.write("      border: .15em solid #bbb7c5;\r\n");
      out.write("      border-right-color: transparent;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      -webkit-animation: spinner .75s linear infinite;\r\n");
      out.write("      animation: spinner .75s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @-webkit-keyframes spinner {\r\n");
      out.write("      100% {\r\n");
      out.write("        -webkit-transform: rotate(360deg);\r\n");
      out.write("        transform: rotate(360deg);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes spinner {\r\n");
      out.write("      100% {\r\n");
      out.write("        -webkit-transform: rotate(360deg);\r\n");
      out.write("        transform: rotate(360deg);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <!-- Page loading scripts-->\r\n");
      out.write("  <script>\r\n");
      out.write("    (function () {\r\n");
      out.write("      window.onload = function () {\r\n");
      out.write("        var preloader = document.querySelector('.page-loading');\r\n");
      out.write("        preloader.classList.remove('active');\r\n");
      out.write("        setTimeout(function () {\r\n");
      out.write("          preloader.remove();\r\n");
      out.write("        }, 2000);\r\n");
      out.write("      };\r\n");
      out.write("    })();\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("  <!-- Vendor Styles-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vendor/simplebar.min.css\" />\r\n");
      out.write("  <!-- Main Theme Styles + Bootstrap-->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/theme.css\">\r\n");
      out.write("  <!-- 채원 직접 작성한 Styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/common.css\">\r\n");
      out.write("  <!-- 인화스타일시트 -->\r\n");
      out.write("  <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/event-main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- Body-->\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-secondary\">\r\n");
      out.write("  <!-- Page loading spinner-->\r\n");
      out.write("  <div class=\"page-loading active\">\r\n");
      out.write("    <div class=\"page-loading-inner\">\r\n");
      out.write("      <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Page container-->\r\n");
      out.write("    <!-- 배경이미지 -->\r\n");
      out.write("    <div class=\"jarallax bg-dark bg-1\" data-jarallax data-speed=\"0.5\" style=\"height: 400px; \">\r\n");
      out.write("      <span class=\"img-overlay bg-transparent opacity-80\"\r\n");
      out.write("        style=\"background-image: linear-gradient(0deg, rgba(31, 27, 45, .7), rgba(31, 27, 45, .7));\"></span>\r\n");
      out.write("      <div class=\"jarallax-img\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/판굿\\(문화재청\\).JPG);\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"page-wrapper bg-2\">\r\n");
      out.write("      <div class=\"container mb-md-4 \">\r\n");
      out.write("        <!-- Page content-->\r\n");
      out.write("        <div class=\"card card-body p-4 p-md-5 shadow-sm\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Search form-->\r\n");
      out.write("          <form class=\"form-group rounded-pill\">\r\n");
      out.write("            <input class=\"form-control\" type=\"text\" placeholder=\"What are you looking for?\">\r\n");
      out.write("            <button class=\"btn btn-lg btn-primary rounded-pill px-sm-4 px-3\" type=\"submit\"><i\r\n");
      out.write("                class=\"fi-search me-sm-2\"></i><span class=\"d-sm-inline d-none\">Search</span></button>\r\n");
      out.write("          </form>\r\n");
      out.write("\r\n");
      out.write("          <!-- 행사 목록 -->\r\n");
      out.write("          <div class=\"row row-cols-lg-3 row-cols-sm-2 row-cols-1 gy-4 gx-3 gx-lg-4 mb-4\">\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\"> \r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/22258_5목중춤_국가무형_은율탈춤_2003_인천_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">은율탈춤</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>인천광역시 남구 종합운동장</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img//121526_한국문화재재단_풍류_공연_64_국가무형_서도소리_2017_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">서도소리</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울시 광화문 샤롯데시어터</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>성인 1만원..</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/8579_사자춤_앉아서_모래기_치기_국가무형_북청사자놀음_2001_서울_기록화_국립무형유산원__.jpg\"\r\n");
      out.write("                    alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">북청사자놀음</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울특별시 문화광장</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/82876_정전_뒤에서_본_전경_국가무형_종묘제례악_2008_서울_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">종료제례학</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울특별시 전통체험실</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/6731_판굿_호허굿_국가무형_임실필봉농악_1999_전북_임실_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">임실필봉농악</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>전북 중앙광장</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/16303_사방작대_국가무형_처용무_2000_서울_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">사방작대</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울 종묘</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/22258_5목중춤_국가무형_은율탈춤_2003_인천_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">은율탈춤</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>인천광역시 남구 종합운동장</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img//121526_한국문화재재단_풍류_공연_64_국가무형_서도소리_2017_기록화_국립무형유산원.jpg\" alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">서도소리</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울시 광화문 샤롯데시어터</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>성인 1만원..</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Item-->\r\n");
      out.write("            <div class=\"col pt-2\">\r\n");
      out.write("              <div class=\"position-relative1\" onclick=\"location.href='event-detail.html';\" style=\"cursor:pointer;\">\r\n");
      out.write("                <div class=\"position-relative mb-3\">\r\n");
      out.write("                  <img class=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/8579_사자춤_앉아서_모래기_치기_국가무형_북청사자놀음_2001_서울_기록화_국립무형유산원__.jpg\"\r\n");
      out.write("                    alt=\"Article img\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"mb-2 fs-lg bih-p-1\"><a class=\"nav-link\">북청사자놀음</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"list-inline mb-0 bih-p-1\">\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>2022.12.1~2022.12.14</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>서울특별시 문화광장</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>무료</b></li><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1\"><b>어린이/청소년/성인</b></li><br><br>\r\n");
      out.write("                  <li class=\"list-inline-item pe-1 bih-m-1\"><span class=\"text-muted\">더보기<i\r\n");
      out.write("                        class=\"fi-arrow-long-right\"></i></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 페이지 넘버링-->\r\n");
      out.write("            <ul class=\"pagination mb-0 bih-m-2\">\r\n");
      out.write("              <li class=\"page-item d-sm-none\"><span class=\"page-link page-link-static\">1 / 8</span></li>\r\n");
      out.write("              <li class=\"page-item active d-none d-sm-block\" aria-current=\"page\"><span class=\"page-link\">1<span\r\n");
      out.write("                    class=\"visually-hidden\">(current)</span></span></li>\r\n");
      out.write("              <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("              <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("              <li class=\"page-item d-none d-sm-block\">...</li>\r\n");
      out.write("              <li class=\"page-item d-none d-sm-block\"><a class=\"page-link\" href=\"#\">8</a></li>\r\n");
      out.write("              <li class=\"page-item\"><a class=\"page-link\" href=\"#\" aria-label=\"Next\"><i class=\"fi-chevron-right\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/simplebar.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/vendor/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("  <!-- Main theme script-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/theme.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/event/event-main.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/event/event-main.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/event/event-main.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
